-- * todoapi 계정 생성 *--
CREATE USER C##TODOAPI IDENTIFIED BY TODOAPI;
GRANT CONNECT, RESOURCE TO C##TODOAPI;
ALTER USER C##TODOAPI DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;


-- * 테이블 및 시퀀스 객체 생성 * --
DROP TABLE TODO;
CREATE TABLE TODO (
    ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(255) NOT NULL,
    STATUS VARCHAR2(50) DEFAULT 'IN_PROGRESS' CHECK(STATUS IN ('IN_PROGRESS', 'COMPLETED')),
    CREATED_AT DATE DEFAULT SYSDATE
);

DROP SEQUENCE SEQ_TODO;
CREATE SEQUENCE SEQ_TODO;