spring.application.name=ems

# database setting
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=C##KH
spring.datasource.password=KH

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mappers/*.xml

# terminal color
spring.output.ansi.enabled=ALWAYS

# logging pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %clr(%-5level){green} %clr(%logger{36}.%M\\(\\)){cyan}: %msg%n

# OpenAI API Key
spring.ai.openai.api-key=${OPENAI_API_KEY}